[library]
path = "${KICAD_LIB_DIR_USER}/Connectors/Ki-Connectors.kicad_sym"

[defaults.geometry]
body_width = 20.0
pin_pitch = 5.0
pin_length = 2.5
body_fill = "background"

[defaults.pin_labels]
show_pin_numbers = true
show_pin_names = false

[[series]]
prefix = "Con"
rows = [1, 2, 3]
schemes = ["R", "S"]
reference = "X"
value = "XX"
display_name = "Разъем универсальный"
show_pin_numbers = true
show_pin_names = false
zero_pad_pins = 2
skip_single_row_non_row = true

[series.scheme_map]
R = "row"
S = "column"
Z = "column_snake"

[series.pins_per_row_by_rows]
"1" = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
"2" = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
"3" = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
